title: "Instalguru"
baseurl: "" # the subpath of your site, e.g. /blog
url: "instalguru.pl" # the base hostname & protocol for your site, e.g. http://example.com
lang: "pl"
photo: "/assets/img/default.jpg"

markdown: kramdown

sass:
  style: compressed

toc:
  min_level: 2
  max_level: 3

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc

collections:
  posts:    
    permalink: /blog/:title:output_ext